import Providers from "@/Providers";
import "../globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Leave on all world",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body>
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
