"use client";
import * as React from "react";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";

export default function CitySelect() {
  return (
    <Autocomplete
      sx={{
        marginTop: 1,
      }}
      id="country-select-demo"
      options={countries}
      autoHighlight
      getOptionLabel={(option) => option.label}
      renderOption={(props, option) => {
        const { key, ...optionProps } = props;
        return (
          <Box
            key={key}
            component="li"
            sx={{ "& > img": { mr: 2, flexShrink: 0 } }}
            {...optionProps}
          >
            {option.label}
          </Box>
        );
      }}
      renderInput={(params) => (
        <TextField
          variant="standard"
          {...params}
          label="CITY"
          inputProps={{
            ...params.inputProps,
            autoComplete: "new-password", // disable autocomplete and autofill
          }}
        />
      )}
    />
  );
}

interface CountryType {
  label: string;
  suggested?: boolean;
}

// From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
const countries: readonly CountryType[] = [
  { label: "Andorra la Vella" },
  { label: "Abu Dhabi" },
  { label: "Dubai" },
  { label: "Kabul" },
  { label: "St. John's" },
  { label: "The Valley" },
  { label: "Tirana" },
  { label: "Yerevan" },
  { label: "Luanda" },
  { label: "Buenos Aires" },
  { label: "Pago Pago" },
  { label: "Vienna" },
  { label: "Sydney" },
  { label: "Oranjestad" },
  { label: "Mariehamn" },
  { label: "Baku" },
  { label: "Sarajevo" },
  { label: "Bridgetown" },
  { label: "Dhaka" },
  { label: "Brussels" },
  { label: "Ouagadougou" },
  { label: "Sofia" },
  { label: "Manama" },
  { label: "Gitega" },
  { label: "Porto-Novo" },
  { label: "Gustavia" },
  { label: "Hamilton" },
  { label: "Bandar Seri Begawan" },
  { label: "Sucre" },
  { label: "Brasília" },
  { label: "Nassau" },
  { label: "Thimphu" },
  { label: "Gaborone" },
  { label: "Minsk" },
  { label: "Belmopan" },
  { label: "Ottawa" },
  { label: "West Island" },
  { label: "Kinshasa" },
  { label: "Bangui" },
  { label: "Brazzaville" },
  { label: "Bern" },
  { label: "Yamoussoukro" },
  { label: "Avarua" },
  { label: "Santiago" },
  { label: "Yaoundé" },
  { label: "Beijing" },
  { label: "Bogotá" },
  { label: "San José" },
  { label: "Havana" },
  { label: "Praia" },
  { label: "Willemstad" },
  { label: "Flying Fish Cove" },
  { label: "Nicosia" },
  { label: "Prague" },
  { label: "Berlin" },
  { label: "Djibouti" },
  { label: "Copenhagen" },
  { label: "Roseau" },
  { label: "Santo Domingo" },
  { label: "Algiers" },
  { label: "Quito" },
  { label: "Tallinn" },
  { label: "Cairo" },
  { label: "El Aaiún" },
  { label: "Asmara" },
  { label: "Madrid" },
  { label: "Addis Ababa" },
  { label: "Helsinki" },
  { label: "Suva" },
  { label: "Palikir" },
  { label: "Tórshavn" },
  { label: "Paris" },
  { label: "Libreville" },
  { label: "London" },
  { label: "St. George's" },
  { label: "Tbilisi" },
  { label: "Accra" },
  { label: "Gibraltar" },
  { label: "Nuuk" },
  { label: "Banjul" },
  { label: "Conakry" },
  { label: "Basse-Terre" },
  { label: "Malabo" },
  { label: "Athens" },
  { label: "Guatemala City" },
  { label: "Hagåtña" },
  { label: "Bissau" },
  { label: "Georgetown" },
  { label: "Hong Kong" },
  { label: "Tegucigalpa" },
  { label: "Zagreb" },
  { label: "Port-au-Prince" },
  { label: "Budapest" },
  { label: "Jakarta" },
  { label: "Dublin" },
  { label: "Jerusalem" },
  { label: "New Delhi" },
  { label: "Baghdad" },
  { label: "Tehran" },
  { label: "Reykjavik" },
  { label: "Rome" },
  { label: "Saint Helier" },
  { label: "Kingston" },
  { label: "Amman" },
  { label: "Tokyo" },
  { label: "Nairobi" },
  { label: "Bishkek" },
  { label: "Phnom Penh" },
  { label: "Tarawa" },
  { label: "Moroni" },
  { label: "Basseterre" },
  { label: "Pyongyang" },
  { label: "Seoul" },
  { label: "Kuwait City" },
  { label: "George Town" },
  { label: "Nur-Sultan" },
  { label: "Vientiane" },
  { label: "Beirut" },
  { label: "Castries" },
  { label: "Vaduz" },
  { label: "Sri Jayawardenepura Kotte" },
  { label: "Monrovia" },
  { label: "Maseru" },
  { label: "Vilnius" },
  { label: "Luxembourg City" },
  { label: "Riga" },
  { label: "Tripoli" },
  { label: "Rabat" },
  { label: "Monaco" },
  { label: "Chișinău" },
  { label: "Podgorica" },
  { label: "Marigot" },
  { label: "Antananarivo" },
  { label: "Majuro" },
  { label: "Skopje" },
  { label: "Bamako" },
  { label: "Naypyidaw" },
  { label: "Ulaanbaatar" },
  { label: "Macau" },
  { label: "Saipan" },
  { label: "Fort-de-France" },
  { label: "Nouakchott" },
  { label: "Plymouth" },
  { label: "Valletta" },
  { label: "Port Louis" },
  { label: "Malé" },
  { label: "Lilongwe" },
  { label: "Mexico City" },
  { label: "Kuala Lumpur" },
  { label: "Maputo" },
  { label: "Windhoek" },
  { label: "Nouméa" },
  { label: "Niamey" },
  { label: "Norfolk Island" },
  { label: "Abuja" },
  { label: "Managua" },
  { label: "Amsterdam" },
  { label: "Oslo" },
  { label: "Kathmandu" },
  { label: "Yaren" },
  { label: "Alofi" },
  { label: "Wellington" },
  { label: "Muscat" },
  { label: "Panama City" },
  { label: "Lima" },
  { label: "Papeete" },
  { label: "Port Moresby" },
  { label: "Manila" },
  { label: "Islamabad" },
  { label: "Warsaw" },
  { label: "Saint-Pierre" },
  { label: "Adamstown" },
  { label: "San Juan" },
  { label: "Lisbon" },
  { label: "Ngerulmud" },
  { label: "Asunción" },
  { label: "Doha" },
  { label: "Saint-Denis" },
  { label: "Bucharest" },
  { label: "Belgrade" },
  { label: "Moscow" },
  { label: "Kigali" },
  { label: "Riyadh" },
  { label: "Honiara" },
  { label: "Victoria" },
  { label: "Khartoum" },
  { label: "Stockholm" },
  { label: "Singapore" },
  { label: "Jamestown" },
  { label: "Ljubljana" },
  { label: "Longyearbyen" },
  { label: "Bratislava" },
  { label: "Freetown" },
  { label: "San Marino" },
  { label: "Dakar" },
  { label: "Mogadishu" },
  { label: "Paramaribo" },
  { label: "Juba" },
  { label: "São Tomé" },
  { label: "San Salvador" },
  { label: "Philipsburg" },
  { label: "Damascus" },
  { label: "Mbabane" },
  { label: "Cockburn Town" },
  { label: "N'Djamena" },
  { label: "Port-aux-Français" },
  { label: "Lomé" },
  { label: "Bangkok" },
  { label: "Dushanbe" },
  { label: "Fakaofo" },
  { label: "Dili" },
  { label: "Ashgabat" },
  { label: "Tunis" },
  { label: "Nukuʻalofa" },
  { label: "Ankara" },
  { label: "Port of Spain" },
  { label: "Funafuti" },
  { label: "Dodoma" },
  { label: "Kyiv" },
  { label: "Kampala" },
  { label: "Washington, D.C." },
  { label: "Washington, D.C." },
  { label: "Montevideo" },
  { label: "Tashkent" },
  { label: "Vatican City" },
  { label: "Kingstown" },
  { label: "Caracas" },
  { label: "Hanoi" },
  { label: "Port Vila" },
  { label: "Mata-Utu" },
  { label: "Apia" },
  { label: "Sana'a" },
  { label: "Mamoudzou" },
  { label: "Pretoria" },
  { label: "Lusaka" },
  { label: "Harare" },
];
